apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: statefulset-lab
spec:
  type: clusterIP
  clusterIP: headless None
  selector:
    app: mongo
    tier: database
    
  ports:
  - port: 27017
    name: web